{
  "Uuid": "de11497f-9956-431f-87fd-1054d7834923",
  "IsCustomNode": false,
  "Description": null,
  "Name": "SwitchJoinOrder",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "import clr\r\nimport System\r\nimport operator\r\nclr.AddReference('ProtoGeometry')\r\nfrom Autodesk.DesignScript.Geometry import *\r\n\r\n# Import DocumentManager and TransactionManager\r\nclr.AddReference(\"RevitServices\")\r\nimport RevitServices\r\nfrom RevitServices.Persistence import DocumentManager\r\nfrom RevitServices.Transactions import TransactionManager\r\n\r\nfrom System.Collections.Generic import *\r\n\r\n# Import RevitAPI\r\nclr.AddReference(\"RevitAPI\")\r\nimport Autodesk\r\nimport Autodesk.Revit.DB as db\r\n\r\n# Just for showing the category and surrender category changing this won't do anything.\r\nmappingDictionary = {\r\n\"Walls\" : (\"Structural Columns\"),\r\n\"Floors\" : (\"Structural Framing\"),\r\n\"Structural Framing\" : (\"None\"),\r\n\"Structural Columns\" : (\"Structural Framing\", \"Floors\", \"Structural Foundations\"),\r\n\"Structural Foundations\" : (\"Floors\", \"Walls\")\r\n\r\n}\r\n\r\ndef createMultiCategoryFilter():\r\n    \"\"\"Create multi category filter instace to use in getAllModelElement\r\n\r\n    Returns:\r\n        obj: filter instace\r\n    \"\"\"\r\n    listOfCategories = list()\r\n    listOfCategories.append(db.BuiltInCategory.OST_Floors)\r\n    listOfCategories.append(db.BuiltInCategory.OST_StructuralColumns)\r\n    listOfCategories.append(db.BuiltInCategory.OST_StructuralFraming)\r\n    listOfCategories.append(db.BuiltInCategory.OST_StructuralFoundation)\r\n    listOfCategories.append(db.BuiltInCategory.OST_Walls)\r\n    iCollectionOfCategoriesForMultiCategoryFIlter = List[db.BuiltInCategory](listOfCategories)\r\n    multiCategoryFilter = db.ElementMulticategoryFilter(iCollectionOfCategoriesForMultiCategoryFIlter)\r\n    return multiCategoryFilter\r\n\r\ndef getAllModelElements(doc):\r\n    \"\"\"get all model using filter from createMultiCategoryFilter\r\n\r\n    Args:\r\n        doc (object): Revit document\r\n\r\n    Returns:\r\n        list: list of elements from filter\r\n    \"\"\"\r\n    multiCategoryFilter = createMultiCategoryFilter()\r\n    allIdsOfModelElements = db.FilteredElementCollector(doc).WherePasses(multiCategoryFilter).WhereElementIsNotElementType().ToElementIds()\r\n    allElementsOfModel = map(lambda x: doc.GetElement(x), allIdsOfModelElements)\r\n    return allElementsOfModel\r\n\r\n# Mape piszemy w schemacie: elementy jakiej kategori mają być nadrzędne nad jakimi kategoriami\r\ndef createMappingDictionary():\r\n    mapType = {\r\n    \"Walls\" : (\"Structural Columns\", \"Walls\"),\r\n    \"Floors\" : (\"Strcutral Framing\", \"Structural Columns\", \"Walls\"),\r\n    \"Structural Framing\" : (\"None\"),\r\n    \"Structural Columns\" : (\"Structural Framing\", \"Floors\", \"Structural Foundations\"),\r\n    \"Structural Foundations\" : (\"Floors\", \"Walls\")\r\n    }\r\n    return mapType\r\n\r\ndef properSwitchOfElements(revitElement, joinedElement, surrenderElementTypes, doc):\r\n    \"\"\"Switch joining order of 2 elements\r\n\r\n    Args:\r\n        revitElement (obj): Primary Revit element\r\n        joinedElement (obj): secondary Revit element\r\n        surrenderElementTypes (tuple): tuple of string representation of surrender category(cutting category of Primary element)\r\n        doc (obj): Revit document\r\n    \"\"\"\r\n    joinedElementCategoryName = joinedElement.Category.Name\r\n    if joinedElementCategoryName in surrenderElementTypes:\r\n        if db.JoinGeometryUtils.IsCuttingElementInJoin(doc, revitElement, joinedElement):\r\n            try:\r\n                db.JoinGeometryUtils.SwitchJoinOrder(doc, revitElement, joinedElement)\r\n            except:\r\n                pass\r\n    else:\r\n        if not db.JoinGeometryUtils.IsCuttingElementInJoin(doc, revitElement, joinedElement):\r\n            try:\r\n                db.JoinGeometryUtils.SwitchJoinOrder(doc, revitElement, joinedElement)\r\n            except:\r\n                pass\r\n\r\n\r\ndef manageJoinedElements(revitElement, doc):\r\n    \"\"\"ultilising previous function to manage joined elements.\r\n\r\n    it'll check with every joined elements to see if joining order is correct.\r\n    Using properSwitchOfElements function.\r\n\r\n    surrenderElementTypes is a tuple of type that would be cutting type of revitElement     \r\n\r\n    Args:\r\n        revitElement (obj): Revit element\r\n        doc (obj): Revit document\r\n    \"\"\"\r\n    joinedElementIds = db.JoinGeometryUtils.GetJoinedElements(doc, revitElement)\r\n    mappingDictionary = createMappingDictionary()\r\n    revitElementCategoryName = revitElement.Category.Name\r\n    surrenderElementTypes = mappingDictionary[revitElementCategoryName]\r\n    for joinedId in joinedElementIds:\r\n        joinedElement = doc.GetElement(joinedId)        \r\n        properSwitchOfElements(revitElement, joinedElement, surrenderElementTypes, doc)\r\n        \r\n\r\ndef main():\r\n    \"\"\"run all function\r\n\r\n    Returns:\r\n        obj: List of Revit elements\r\n    \"\"\"\r\n    doc = DocumentManager.Instance.CurrentDBDocument\r\n    allModelElements = getAllModelElements(doc)\r\n    lst = list()\r\n    TransactionManager.Instance.EnsureInTransaction(doc)\r\n    for revitElement in allModelElements:\r\n        lst.append(manageJoinedElements(revitElement, doc))\r\n    TransactionManager.Instance.TransactionTaskDone()\r\n    return allModelElements\r\nOUT = main()\r\n",
      "VariableInputPorts": true,
      "Id": "0de6f1d4be51463b8680615647f6de5e",
      "Inputs": [
        {
          "Id": "344771d500044928a5cf9cc6b89c2744",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "672822bd0bda485092e1972dfe44c8a6",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded IronPython script."
    },
    {
      "ConcreteType": "CoreNodeModels.Input.BoolSelector, CoreNodeModels",
      "NodeType": "BooleanInputNode",
      "InputValue": false,
      "Id": "d1ca3b2a564448dcba9658b1dbd8e259",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "2751206f48f446cf928c0708398ab376",
          "Name": "",
          "Description": "Boolean",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Selection between a true and false."
    }
  ],
  "Connectors": [
    {
      "Start": "2751206f48f446cf928c0708398ab376",
      "End": "344771d500044928a5cf9cc6b89c2744",
      "Id": "d8e2197cf289475087ed00d7738cf7b2"
    }
  ],
  "Dependencies": [],
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": true,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.0.3.8810",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "NodeViews": [
      {
        "Id": "0de6f1d4be51463b8680615647f6de5e",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "SwitchJoinOrder",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 591.99365559504986,
        "Y": 300.72181101079025
      },
      {
        "Id": "d1ca3b2a564448dcba9658b1dbd8e259",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Name": "Boolean",
        "ShowGeometry": true,
        "Excluded": false,
        "X": 372.87145150270072,
        "Y": 316.96985732861003
      }
    ],
    "Annotations": [],
    "X": -218.26868671724435,
    "Y": -106.06495837117063,
    "Zoom": 1.255844835613146
  }
}